"""add_energy_fields_to_project

Revision ID: 041743a53b78
Revises: 1e6addd0c4ab
Create Date: 2026-03-03 21:56:45.246739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041743a53b78'
down_revision: Union[str, Sequence[str], None] = '1e6addd0c4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('system_size_kwp', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('panel_count', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('inverter_type', sa.String(), nullable=True))
    op.add_column('project', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'longitude')
    op.drop_column('project', 'latitude')
    op.drop_column('project', 'inverter_type')
    op.drop_column('project', 'panel_count')
    op.drop_column('project', 'system_size_kwp')
    # ### end Alembic commands ###
