"""Add TMS models

Revision ID: 4d3f05cb30e4
Revises: 7f677d99541a
Create Date: 2026-03-12 21:44:29.659013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3f05cb30e4'
down_revision: Union[str, Sequence[str], None] = '7f677d99541a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('license_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_TRANSIT', 'OFF_DUTY', name='driverstatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('capacity_weight', sa.Float(), nullable=True),
    sa.Column('capacity_volume', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_TRANSIT', 'MAINTENANCE', name='vehiclestatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_license_plate'), 'vehicle', ['license_plate'], unique=True)
    op.create_table('projectitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('issued_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectitem_id'), 'projectitem', ['id'], unique=False)
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_number', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('route_summary', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_id'), 'trip', ['id'], unique=False)
    op.create_index(op.f('ix_trip_trip_number'), 'trip', ['trip_number'], unique=True)
    op.add_column('shipment', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.add_column('shipment', sa.Column('po_id', sa.Integer(), nullable=True))
    op.add_column('shipment', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipment', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'shipment', 'trip', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'shipment', 'purchaseorder', ['po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'project_id')
    op.drop_column('shipment', 'po_id')
    op.drop_column('shipment', 'trip_id')
    op.drop_index(op.f('ix_trip_trip_number'), table_name='trip')
    op.drop_index(op.f('ix_trip_id'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_projectitem_id'), table_name='projectitem')
    op.drop_table('projectitem')
    op.drop_index(op.f('ix_vehicle_license_plate'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
