"""create_setting_table_v2

Revision ID: 4fb1952d04c7
Revises: ee24c731f796
Create Date: 2026-03-03 22:39:36.285705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb1952d04c7'
down_revision: Union[str, Sequence[str], None] = 'ee24c731f796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_category'), 'setting', ['category'], unique=False)
    op.create_index(op.f('ix_setting_id'), 'setting', ['id'], unique=False)
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_index(op.f('ix_setting_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_category'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
