"""Upgrade inventory to professional warehouse schema

Revision ID: 7f677d99541a
Revises: 4fb1952d04c7
Create Date: 2026-03-09 22:09:45.733104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f677d99541a'
down_revision: Union[str, Sequence[str], None] = '4fb1952d04c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_barcode'), 'inventory_item', ['barcode'], unique=True)
    op.create_index(op.f('ix_inventory_item_category'), 'inventory_item', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_item_id'), 'inventory_item', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_name'), 'inventory_item', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_item_sku'), 'inventory_item', ['sku'], unique=True)
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_code'), 'warehouse', ['code'], unique=True)
    op.create_index(op.f('ix_warehouse_id'), 'warehouse', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_name'), 'warehouse', ['name'], unique=False)
    op.create_table('bin_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_location_code'), 'bin_location', ['code'], unique=False)
    op.create_index(op.f('ix_bin_location_id'), 'bin_location', ['id'], unique=False)
    op.create_table('inventory_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='auditstatus'), nullable=True),
    sa.Column('audit_type', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_audit_id'), 'inventory_audit', ['id'], unique=False)
    op.create_table('stock_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_id'), 'stock_transfer', ['id'], unique=False)
    op.create_table('audit_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['inventory_audit.id'], ),
    sa.ForeignKeyConstraint(['bin_id'], ['bin_location.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_item_id'), 'audit_item', ['id'], unique=False)
    op.create_table('inventory_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_on_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bin_location.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_level_id'), 'inventory_level', ['id'], unique=False)
    op.create_table('stock_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', 'AUDIT', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['bin_location.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transaction_id'), 'stock_transaction', ['id'], unique=False)
    op.drop_index(op.f('ix_inventoryitem_category'), table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_id'), table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_name'), table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_sku'), table_name='inventoryitem')
    op.drop_table('inventoryitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventoryitem_pkey'))
    )
    op.create_index(op.f('ix_inventoryitem_sku'), 'inventoryitem', ['sku'], unique=True)
    op.create_index(op.f('ix_inventoryitem_name'), 'inventoryitem', ['name'], unique=False)
    op.create_index(op.f('ix_inventoryitem_id'), 'inventoryitem', ['id'], unique=False)
    op.create_index(op.f('ix_inventoryitem_category'), 'inventoryitem', ['category'], unique=False)
    op.drop_index(op.f('ix_stock_transaction_id'), table_name='stock_transaction')
    op.drop_table('stock_transaction')
    op.drop_index(op.f('ix_inventory_level_id'), table_name='inventory_level')
    op.drop_table('inventory_level')
    op.drop_index(op.f('ix_audit_item_id'), table_name='audit_item')
    op.drop_table('audit_item')
    op.drop_index(op.f('ix_stock_transfer_id'), table_name='stock_transfer')
    op.drop_table('stock_transfer')
    op.drop_index(op.f('ix_inventory_audit_id'), table_name='inventory_audit')
    op.drop_table('inventory_audit')
    op.drop_index(op.f('ix_bin_location_id'), table_name='bin_location')
    op.drop_index(op.f('ix_bin_location_code'), table_name='bin_location')
    op.drop_table('bin_location')
    op.drop_index(op.f('ix_warehouse_name'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_id'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_code'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_inventory_item_sku'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_name'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_category'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_barcode'), table_name='inventory_item')
    op.drop_table('inventory_item')
    # ### end Alembic commands ###
