"""add_hr_fields_to_user

Revision ID: ddf07c225cd2
Revises: 041743a53b78
Create Date: 2026-03-03 22:14:22.328260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf07c225cd2'
down_revision: Union[str, Sequence[str], None] = '041743a53b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('department', sa.String(), nullable=True))
    op.add_column('user', sa.Column('position', sa.String(), nullable=True))
    op.add_column('user', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_department'), 'user', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_department'), table_name='user')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'join_date')
    op.drop_column('user', 'position')
    op.drop_column('user', 'department')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
